### ISSUE TITLE
Submission_problem

### ISSUE THREAD

**Issue by Mahmuda212** [Mahedi-61/MIU_Spring_2019#4]
After Submitting my file this folder is shown failed :
can not upload file through csv format.........
[submission1.docx](https://github.com/Mahedi-61/MIU_Spring_2019/files/3026262/submission1.docx)
Error:
![sub](https://user-images.githubusercontent.com/46498359/55285323-4b56bf00-53ab-11e9-9692-3c9d07302f04.png)
![er](https://user-images.githubusercontent.com/46498359/55285324-4bef5580-53ab-11e9-9927-4cfce6150273.png)

**Comment by Mahedi-61** [comment]
Oh. Sorry for my spelling mistake. 

Just, change the column name to "Label" in the submission file.

**Comment by Mahmuda212** [comment]
Thank you sir.I also thought it 
Successfully Submitted our file
